### ISSUE TITLE
popular micro:bit programs and needed tiles

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#12]
## Simple programs

- flashing heart: https://makecode.microbit.org/projects/flashing-heart
- smiley buttons: https://makecode.microbit.org/projects/smiley-buttons
- dice: https://makecode.microbit.org/projects/dice
- clap lights: https://makecode.microbit.org/projects/v2-clap-lights
- rock, paper, scissors: https://makecode.microbit.org/projects/rock-paper-scissors
- teleport duck: https://www.microbit.org/projects/make-it-code-it/teleporting-duck/

For more programs. see the carousels at https://makecode.microbit.org/. Feel free to add to the list!

## Needed tiles

- pipe: https://github.com/microsoft/microcode/issues/72
- show number
- shake: https://github.com/microsoft/microcode/issues/57
- random number generation (1..N): https://github.com/microsoft/microcode/issues/13
- action: pause

## Done:
- button
- show icon
- radio send
- radio receive
- timer 
- microphone (soft, loud, ???)
- speaker

## Other concepts
- variable slots (boolean, number)???

**Comment by eanders-ms** [comment]
Some hypothetical microcode...

Constraints: Keep it to one page, code should read like natural language.


### Dice

```
WHEN [shake] DO [show] [random (1) to (6)]
```

* "show" should be able to determine the type of the value (icon, number, string, whether single or a set of values) and handle it correctly.
* "random" is a modifier with field editor for inputting the range.
* Number literals come from a field editor. Implies one field editor can spawn another.



### Rock Paper Scissors

```
WHEN [shake] DO [set][(hand)][random (1) to (3)]
WHEN [(hand)][equals][1] DO [show][(rock icon)]
WHEN [(hand)][equals][2] DO [show][(paper icon)]
WHEN [(hand)][equals][3] DO [show][(scissors icon)]
```

* "hand" is a user-created variable. UI for creating/picking variables TBD.
* Number literals come from a field editor.


### Flashing Heart

This one is tricky. Here are some ideas:

```
WHEN [timer (1s) (50%)] DO [show][(heart icon)]
WHEN [not] [timer (1s) (50%)] DO [show][(empty icon)]
```

Notes
* Supporting "not" would require some changes to the current editor due to the assumption that the first tile is always a sensor. This was previously handled by the rule trigger condition, but that was an advanced feature, and these canonical examples need to be kept simple.
* "timer" has two arguments here: the period/frequency, and pulse width. 1s and 50% should be the defaults.

```
WHEN [timer (1s) (50%)] DO [show][(heart icon)]
WHEN [timer (1s) (-50%)] DO [show][(empty icon)]
```

* Negative pulse width as a trick to negate the signal. Not straight forward, and not generally applicable.

```
WHEN [timer (1s) (50%)] DO [show][(heart icon)] ELSE [show][(empty icon)]
```

* Introduction of an ELSE clause. I'm not opposed to this.


### Smiley buttons

```
WHEN [A] DO [show][(smiley icon)]
WHEN [B] DO [show][(frowny icon)]
```


### Clap Lights

```
WHEN [hear][loud] DO [toggle (lights on)]
WHEN [(lights on)] DO [show][(light icon)] ELSE [show][(empty icon)]
```

* "toggle" avoids a messy statement like "[set][(lights on)][not][(lights on)]", but we'll need to address how to do this kind of thing. Someone will want to do math.
* ELSE is coming in handy here too.


### Teleporting Duck

```
WHEN [once] DO [set radio group][23]
WHEN [shake] DO [show][(empty icon)][,][radio send ("DUCK")]
WHEN [radio receive ("DUCK")] DO [show (duck icon)]
```

* "once" sensor is like the implicit "always", but only fires once.
* "," chaining operator allows multiple actions on the DO side. We might consider this. Alternatively, introduce child rules (see below)
* "DUCK" is a string literal from a field editor

### Teleporting Duck (child rules)

```
WHEN [once] DO [set radio group][23]
WHEN [shake] DO
	WHEN DO [show (empty icon)]
	WHEN DO [radio send ("DUCK")]
```

Child rules make the program more readable, but they're less discoverable than "[,]". Of the two, I prefer child rules, mainly for readability.
