### ISSUE TITLE
capture language design choices in documentation

### ISSUE THREAD

**Issue by pelikhan** [microsoft/microcode#316]
Why is it "store x values" rather "values store x"?

**Comment by whaleygeek** [comment]
I posited this question a while back. If you throw a dice and store it in a variable, modelling unplugged you would throw the dice first, then write that number in the box representing x. We say 'store in x, throw dice' because assignment is right to left in traditional programming languages.

But is it a conceptual or a pedagogical priority when teaching young children, and if it looks odd to adults, does it still look odd to young children? Do they stumble when upgrading to real languages if we present it conceptually consistent or traditionally consistent?

Assignment form is one of many design choices made in language design.

An interesting research question, but also recording the design choices (where an explicit or implicit choice was made) is an important step in both preserving conceptual integrity, but also explaining why things were dine a specific way, what was the overriding principles and priorities at play when the language was designed?

**Comment by whaleygeek** [comment]
P S. This is not a piece about what is right or wrong, it is about the guiding principles that drove one method over another.

**Comment by ramseyball** [comment]
Guiding principle, inherited from Kodu, is that the do section starts with a command followed by parameters to the command. The same principle is active in the when section, which starts with an event and is followed by event parameters.

We use the yellow arrows to show which way values flow.

**Comment by ramseyball** [comment]
I originally thought we could redo Kodu so values always flowed from left to right, but the complications this introduced in the editing model were substantial.

**Comment by ramseyball** [comment]
@whaleygeek - have you seen https://microsoft.github.io/microcode/docs/language?

**Comment by whaleygeek** [comment]
Ooo thanks @ramseyball I will take a proper look! I only recently discovered this fab project as a result of some tweets you sent, so am still exploring it all, but it is a super piece of work!! Running the IDE on a kittenbot arcade is an amazing advancement!!! (Always a huge fan of your work!)
