### ISSUE TITLE
proper deleting of filter/modifier tiles

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#32]
When changing a sensor or actuator, the editor does not get rid of incompatible tiles.

**Comment by eanders-ms** [comment]
Behavior in Kodu was to delete tiles from the first incompatible one onward. Behavior in Spark was non-destructive; it would overlay an exclamation icon on the incompatible tile. Going with deletion is probably fine for microcode, at least initially, because programs will tend to be small / losses minor.

**Comment by pelikhan** [comment]
Incompatible tiles may crash jacscript

**Comment by ramseyball** [comment]
Whenever a tile is changed to a different kind, we should delete everything to right of that tile. For example, if screen is changed to switch page, all led icons to right of screen tile should be deleted. The (safe) assumption is that if you change the kind of tile then the set of tiles permitted to the right may change, but if you change a tile and the kind remains the same, then set of tiles permitted remain same.

**Comment by ramseyball** [comment]
This is more extreme than what Eric suggested:

> Behavior in Kodu was to delete tiles from the first incompatible one onward. 

this would be straightforward to implement too.

**Comment by pelikhan** [comment]
This happens very often when a kids hacks an existing script.
