### ISSUE TITLE
add user program as "sample"

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microcode#380]
we need a way to create backup of a user-created program so that it can be restored.

**Comment by pelikhan** [comment]
you could add a "floppy disk icon" that lets you save the current program in predefined sample locations (probably 3 slots to keep the current grid look)


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: Tom Ball ***@***.***>
Sent: Wednesday, January 11, 2023 9:13 AM
To: microsoft/microcode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/microcode] add user program as "sample" (Issue #380)


we need a way to create backup of a user-created program so that it can be restored.

**Comment by tballmsft** [comment]
TODO:

- [ ] floppy disk icon in upper left of editor, when pressed displays modal for saving to one of three slots
- [ ] add floppy disk icon to home screen, selecting it allows you to load one of three slots into editor (overwriting existing program)

**Comment by pelikhan** [comment]
Would be good to document how this works.
